mod 'puppet/nginx', '1.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
mod 'puppetlabs-inifile', '4.1.0'
mod 'puppet-archive', '4.4.0'
